name: Test
on: [workflow_dispatch]
        
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:   
      - name: Say hello
        uses: 0x7878/Github-Bootcamp/hello-world-docker-action@v1
        with:
          who-to-greet: '@0x7878'
